package ar.edu.unlu.poo.burako.modelo;

public enum Eventos {

    NUEVO_MENSAJE,
    MOSTRAR_JUGADORES,
    ABANDONAR_PARTIDA,
    CAMBIO_TURNO,
    CAMBIO_FICHAS_ATRIL,
    PUNTAJE,
    CAMBIO_JUGADAS_OPONENTE,
    CANTIDAD_FICHAS_ATRIL,
    CANTIDAD_FICHAS_MAZO,
    CAMBIO_FICHAS_POZO,
    TOMAR_MUERTO,
    PARTIDA
}
